remotes:
  diskstation: 
    url: rsync://$USER@192.168.1.50
    auth: RSYNC_PASSWORD
paths:
  documents:
    from: $HOME/Documents/
    to: diskstation:/Documents
    exclude:
      - \#recycle/
    reciprocal: true
  music:
    from: $HOME/Music/
    to: diskstation:/Music
    reciprocal: false
  photo:
    from: $HOME/Pictures/
    to: diskstation:/photo
    reciprocal: false
  videos:
    from: $HOME/Videos/
    to: diskstation:/Videos
    reciprocal: false
  workspace: 
    from: $HOME/workspace/
    to: diskstation:/backups/home/workspace
    reciprocal: false
    exclude:
      - .git/
      - .cache/
  home:
    from: $HOME/
    to: diskstation:/backups/home/$(hostname)/$USER
    exclude:
      - Documents
      - Music
      - Videos
      - Pictures
      - workspace
      - Downloads
      - tmp
      - .git/
      - .cache/
    reciprocal: false
